### ISSUE TITLE
Research Mixture of experts

### ISSUE THREAD

**Issue by new5558** [OpenThaiGPT/openthaigpt-pretraining#30]
- Switch Transformers: Huggingface
- ST-MOE

**Comment by pamsmi** [comment]
ขออภัยค่ะ ช่วงนี้ บังเอิญงานส่วนตัวเข้า เลยยังไม่ได้มีโอกาส review ให้ต่อค่ะ 
แตขอส่ง ไฟล์สรุป ที่ เรียบเรียง ไว้ (คือ แทบจะ copy เนื้อหา มาใส่สไลด์ ไว้ให้ ค่ะ เผื่อ ได้มีโอกาสเรียนรู้ร่วมกันค่ะ :-)  

และไม่มั่นใจว่า ทีมงาน ต้องการ หรือ ขาดเหลือ ส่วนใด ค่ะ เพราะ โดยส่วนตัว เอง ก็ยังแค่เรียนรู้ AI พื้นฐาน เท่านั้น ก็เลยรู้สึกว่า อะไร ก็ยังไม่รู้ 55 

https://drive.google.com/drive/folders/1W_nOgvL8I9t5k3lh-YteWIp3LnjH0swI?usp=sharing

**Comment by pamsmi** [comment]
STABLEMOE: Stable Routing Strategy for Mixture of Experts
https://aclanthology.org/2022.acl-long.489.pdf   

"The routing fluctuation tends to harm sample efficiency because the same input updates different experts but only one is finally used. 

In this paper, we propose STABLEMOE with two training stages to address the routing fluctuation problem. 

In the first training stage, we learn a balanced and cohesive routing strategy and distill it into a lightweight router decoupled from the backbone model. 

In the second training stage, we utilize the distilled router to determine the token-to-expert assignment and freeze it for a stable routing strategy. We validate our method on language modeling and multilingual machine translation.

The results show that STABLEMOE outperforms existing MoE methods in terms of both convergence speed and performance.
The code is available at https://github.com/Hunter-DDM/stablemoe "

**Comment by pamsmi** [comment]
Awesome-Mixture-of-Experts-Papers
https://github.com/codecaution/Awesome-Mixture-of-Experts-Papers

ลิ้งค์รวบรวม paper เกี่ยวกับ  Mixture-of-Experts (MoE) ตั้งแต่ปี 2017 - 2022
มีการจัดหมวดหมู่ ของ Algorithm, System, Application รวมถึง Open-Source System

**Comment by pamsmi** [comment]
slide รวบรวม abstract ของ papers เกี่ยวกับ algorithms ปี 2021 - 2022 
https://drive.google.com/drive/folders/1W_nOgvL8I9t5k3lh-YteWIp3LnjH0swI?usp=sharing 
หวังว่าจะสะดวก ในการอ่าน สำหรับทีมพัฒนาโมเดล นะคะ 
อักษรสีแดง คือ จุดอ่อน ที่แต่ละ paper พยายาม จะแก้ไข 

รวบรวมจากบทความ  Awesome-Mixture-of-Experts-Papers
https://github.com/codecaution/Awesome-Mixture-of-Experts-Papers
